apiVersion: v1
kind: Secret

metadata:
  name: todo-secret
  namespace: todo-app

type: Opaque

stringData:
  SECRET_KEY: mysecretkey

  MONGO_URI: mongodb://admin:admin123@mongodb-service:27017/todoapp?authSource=admin

  MONGO_USERNAME: admin
  MONGO_PASSWORD: admin123